### ISSUE TITLE
Minor Updates

### ISSUE THREAD

**Issue by umutphp** [RasimCem/Laravel-package#1]
Hi @RasimCem ,

Many thanks for the quick response. I have succesfully installed your package to a fresh Laravel app.

![image](https://user-images.githubusercontent.com/3245166/191542918-3334a8ab-849a-46f7-8f8a-c6382708f2d3.png)

I think there is a misunderstanding in the case. You are grouping the quotes by category but we want to group the quotes according to the page slugs.

Additionally, we do not want to add your component to every blade. When a page is rendered, a random quote (select randomly from the list of the page) should be displayed. If there is no quote configured at `quotes.php` file, we can skip displaying a quote.

**Comment by RasimCem** [comment]
Instead of adding components to every blade, can I include a JavaScript file? Or you just don't want any calling operation(function etc.) on the blade? @umutphp

**Comment by umutphp** [comment]
@RasimCem You can do with a JavaScript file but we prefer you to solve it in Laravel.

**Comment by umutphp** [comment]
@RasimCem We have one minor problem. Your package shows all the quotes under the page. The case was to show a random quote from the list.

**Comment by RasimCem** [comment]
I just pushed the commits. Now, quotes are showing randomly. @umutphp
